[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Davi", email = "aaa@aaa"},
]
dependencies = [
    "django>=4.1.7",
    "djangorestframework>=3.14.0",
    "django-cors-headers>=4.2.0",
]
requires-python = ">=3.10"
license = {text = "MIT"}
